In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer

# Exemple de dataset (chaque ligne est une série temporelle)
data = pd.read_csv("/kaggle/input/projet-data/test.csv")

# Convertir en DataFrame
df = pd.DataFrame(data)

# Créer un imputer KNN (avec k=2 voisins par défaut)
imputer = KNNImputer(n_neighbors=65)

# Transposer pour appliquer KNN ligne par ligne
df_imputed = imputer.fit_transform(df.T)

# Re-transposer pour retrouver la structure originale
df_final = pd.DataFrame(df_imputed.T, columns=df.columns)

# Afficher le résultat
print(df_final)

idx_with_nan = data.isna().values.flatten()
pred =  df_final.values.flatten()[idx_with_nan]
submission_example = pd.DataFrame(
    data={'ID': [i for i in range(len(pred))],
          'TARGET': pred
          }
    )
print(submission_example.to_csv('step4_submission_example.csv', index=False))
print(submission_example.isnull().values.any())
pred.shape


             0         1         2         3         4      5         6  \
0     0.243000  0.216000  1.045000  0.621000  0.963000  0.405  0.437000   
1     0.095692  0.069246  0.104323  0.065138  0.074338  0.094  0.044000   
2     0.102000  0.058000  0.050000  0.065000  0.063000  0.105  0.069000   
3     0.347000  0.315000  0.268000  0.288000  0.314000  0.325  0.274000   
4     0.320000  0.274000  0.284000  0.568000  1.312000  1.687  1.326000   
...        ...       ...       ...       ...       ...    ...       ...   
3122  0.047862  0.055677  0.046369  0.048908  0.049000  0.050  0.044769   
3123  0.136000  0.207000  0.127000  0.167000  0.148000  0.063  0.137000   
3124  0.180000  0.125000  0.049000  0.049000  0.048000  0.049  0.046000   
3125  0.117000  0.101000  0.168000  0.102000  0.103000  0.168  0.105000   
3126  0.192000  0.158000  0.136000  0.038000  0.088000  0.075  0.163000   

             7         8      9  ...     12854     12855     12856     12857  \
0     0.668000  0.2

(12058326,)

In [2]:
pred

array([0.48558462, 0.52893846, 0.64502308, ..., 0.16552308, 0.16312308,
       0.21256923])

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

# Charger l'exemple de train (séries complètes)
train = pd.read_csv("/kaggle/input/projet-data/train.csv")

# Charger l'exemple de test (séries incomplètes avec NaN)
test = pd.read_csv("/kaggle/input/projet-data/test.csv")

# Concaténer train et test en une seule DataFrame
df_combined = pd.concat([train, test], ignore_index=True)


# Créer un imputer KNN (avec k=40 voisins)
imputer = KNNImputer(n_neighbors=42)

# Transposer pour appliquer KNN ligne par ligne
df_imputed = imputer.fit_transform(df_combined_scaled.T)  # Appliquer KNN sur les lignes après transposition

# Re-transposer pour retrouver la structure originale


             0         1         2         3         4         5         6  \
0     0.837046  1.274489  1.602556  2.439697  1.784729  1.353685  1.495099   
1     0.015207  0.555886 -0.413077 -0.674284 -0.448132 -0.683312 -0.483695   
2    -0.735448 -0.571186 -0.502002 -0.622557 -0.575842 -0.452313 -0.015153   
3    -0.573669 -0.429987 -0.158159 -0.153563 -0.382218 -0.166713 -0.119779   
4     0.008736 -0.026560  0.283502  0.253358  0.627102  0.488486  0.562564   
...        ...       ...       ...       ...       ...       ...       ...   
6249 -0.616469 -0.593217 -0.651732 -0.634754 -0.660495 -0.648989 -0.628550   
6250 -0.530528 -0.273659 -0.421970 -0.239775 -0.266867 -0.590913 -0.260796   
6251 -0.435617 -0.480415 -0.653175 -0.646696 -0.678834 -0.649713 -0.674750   
6252 -0.571512 -0.540929 -0.300439 -0.463927 -0.452252 -0.149913 -0.406362   
6253 -0.409733 -0.397208 -0.395292 -0.684630 -0.514047 -0.540513 -0.142523   

             7         8         9  ...     12854     12855    

In [4]:

df_final = pd.DataFrame(df_imputed.T, columns=df_combined.columns)
df_final = pd.DataFrame(scaler.inverse_transform(df_final), columns=df_combined.columns)
# Afficher le résultat imputé
print(df_final)

# Extraire uniquement les séries de test après l'imputation
df_test_imputed = df_final[len(train):]  # Récupérer uniquement la partie imputée de test

# Identifier les indices de NaN dans les données originales de test
idx_with_nan = test.isna().values.flatten()

# Extraire les prédictions imputées pour ces indices
pred = df_test_imputed.values.flatten()[idx_with_nan]

# Créer un fichier de soumission
submission_example = pd.DataFrame(
    data={'ID': [i for i in range(len(pred))],
          'TARGET': pred
    }
)





             0         1         2         3         4         5         6  \
0     0.770000  0.821000  0.810000  0.944000  0.646000  0.526000  0.523000   
1     0.389000  0.536000  0.130000  0.041000  0.104000  0.041000  0.088000   
2     0.041000  0.089000  0.100000  0.056000  0.073000  0.096000  0.191000   
3     0.116000  0.145000  0.216000  0.192000  0.120000  0.164000  0.168000   
4     0.386000  0.305000  0.365000  0.310000  0.365000  0.320000  0.318000   
...        ...       ...       ...       ...       ...       ...       ...   
6249  0.096158  0.080262  0.049487  0.052463  0.052452  0.049172  0.056156   
6250  0.136000  0.207000  0.127000  0.167000  0.148000  0.063000  0.137000   
6251  0.180000  0.125000  0.049000  0.049000  0.048000  0.049000  0.046000   
6252  0.117000  0.101000  0.168000  0.102000  0.103000  0.168000  0.105000   
6253  0.192000  0.158000  0.136000  0.038000  0.088000  0.075000  0.163000   

             7         8      9  ...     12854     12855    128

In [7]:
# Sauvegarder le fichier de soumission
submission_example.to_csv('knn_optimase.csv', index=False)

# Vérifier si des NaN sont présents dans la soumission (cela ne devrait pas être le cas)
print(submission_example.isnull().values.any())

# Afficher la forme des prédictions
print(pred.shape)

False
(12058326,)


In [9]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from scipy.signal import savgol_filter



test = pd.DataFrame(df_test_imputed).interpolate(method='linear', axis=1)

test= test.apply(lambda row: savgol_filter(row, window_length=11, polyorder=2), axis=1)




In [15]:
b=np.array(test).flatten()

In [21]:
b.shape

(3127,)

In [23]:
b



array([array([0.33655245, 0.47325734, 0.57481772, ..., 1.02248252, 0.84674126,
              0.61894406])                                                    ,
       array([0.14170501, 0.12047561, 0.1026103 , ..., 0.6607258 , 0.54536051,
              0.40277433])                                                    ,
       array([0.07342967, 0.07400541, 0.0742956 , ..., 0.20055272, 0.21291255,
              0.2220202 ])                                                    ,
       ...,
       array([0.16047552, 0.11962657, 0.08667739, ..., 0.391974  , 0.38058432,
              0.36367301])                                                    ,
       array([0.11646853, 0.12015105, 0.12299907, ..., 0.47237756, 0.50084513,
              0.53492238])                                                    ,
       array([0.16466434, 0.14584755, 0.13051329, ..., 0.26731515, 0.27849091,
              0.29536364])                                                    ],
      dtype=object)

In [31]:
flat_arr = np.hstack(b)


In [32]:
flat_arr=flat_arr[idx_with_nan] 

In [34]:
flat_arr

array([0.26075745, 0.27872068, 0.30867257, ..., 0.73790904, 0.72938442,
       0.87721316])

In [37]:
pred=flat_arr

In [38]:
submission_example = pd.DataFrame(
    data={'ID': [i for i in range(len(pred))],
          'TARGET': pred
    }
)

In [39]:
submission_example.to_csv('knn_optimase_interpolate.csv', index=False)

# Vérifier si des NaN sont présents dans la soumission (cela ne devrait pas être le cas)
print(submission_example.isnull().values.any())

# Afficher la forme des prédictions
print(pred.shape)

False
(12058326,)


In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

# Charger les données
data_train = pd.read_csv("/kaggle/input/projet-data/train.csv")
data_test = pd.read_csv("/kaggle/input/projet-data/test.csv")

# 🚀 Préparer les données d'entraînement
X_train, y_train = [], []

# Créer les données pour l'entraînement avec les indices des valeurs manquantes comme features
for index, row in data_train.iterrows():
    known_indices = np.where(~np.isnan(row))[0]  # Indices des valeurs connues
    X_train.extend(known_indices.reshape(-1, 1))  # Ajouter les indices des valeurs connues
    y_train.extend(row[known_indices])  # Ajouter les valeurs connues

# Convertir en array numpy pour entraîner le modèle
X_train = np.array(X_train)
y_train = np.array(y_train)

# Entraîner un Random Forest sur toutes les séries
rf = RandomForestRegressor(n_estimators=1, random_state=42)
rf.fit(X_train, y_train)
i=0
# 🚀 Imputer les données manquantes dans le dataset test
data_test_imputed = data_test.copy()
for index, row in data_test.iterrows():
    print(i)
    test_series = np.array(row)  # Série temporelle du test
    missing_indices = np.where(np.isnan(test_series))[0]  # Indices des valeurs manquantes

    if len(missing_indices) > 0:
        # Prédire les valeurs manquantes
        X_missing = missing_indices.reshape(-1, 1)  # Les indices des valeurs manquantes
        y_pred = rf.predict(X_missing)  # Prédictions

        # Remplacer les valeurs manquantes dans la série
        test_series[missing_indices] = y_pred
        data_test_imputed.iloc[index] = test_series  # Mettre à jour la ligne dans le DataFrame
        i=i+1
# ✅ Résultat après imputation
print(data_test_imputed)


<ipython-input-1-735081c0cd0b>:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y_train.extend(row[known_indices])  # Ajouter les valeurs connues


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [5]:
idx_with_nan = data_test.isna().values.flatten()
pred =  data_test_imputed.values.flatten()[idx_with_nan]
submission_example = pd.DataFrame(
    data={'ID': [i for i in range(len(pred))],
          'TARGET': pred
          }
    )
print(submission_example.to_csv('rdforest1.csv', index=False))
print(submission_example.isnull().values.any())
pred.shape

None
False


(12058326,)

In [6]:
pip install catboost


Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.preprocessing import StandardScaler

# Charger les données
train = pd.read_csv("/kaggle/input/projet-data/train.csv")
test = pd.read_csv("/kaggle/input/projet-data/test.csv")

# Créer une copie pour l'imputation
data_test_imputed = test.copy()

# Normalisation des données (optionnel, dépend du dataset)
scaler = StandardScaler()
data_combined = pd.concat([train, test], ignore_index=True)
data_combined_scaled = scaler.fit_transform(data_combined)

# Appliquer CatBoost pour chaque ligne avec des valeurs manquantes
for index, row in test.iterrows():
    # Extraire la série temporelle complète
    train_series = np.array(train.iloc[index])
    test_series = np.array(row)
    
    # Trouver les indices des valeurs connues et manquantes
    known_indices = np.where(~np.isnan(test_series))[0]
    missing_indices = np.where(np.isnan(test_series))[0]
    
    if len(missing_indices) > 0:
        # Préparer les données d'entraînement avec les indices des valeurs connues
        X_train = known_indices.reshape(-1, 1)  # Indices des valeurs connues
        y_train = train_series[known_indices]   # Valeurs correspondantes dans train

        # Initialiser le modèle CatBoostRegressor
        model = CatBoostRegressor(iterations=100, learning_rate=0.05, depth=6, cat_features=[], verbose=0)
        
        # Entraîner le modèle sur les données connues
        model.fit(X_train, y_train)

        # Prédire les valeurs manquantes
        X_missing = missing_indices.reshape(-1, 1)
        y_pred = model.predict(X_missing)

        # Remplir les valeurs manquantes
        test_series[missing_indices] = y_pred
        data_test_imputed.iloc[index] = test_series

# Résultat après imputation
print(data_test_imputed)

# Sauvegarder les résultats dans un fichier CSV
data_test_imputed.to_csv('catboost_imputed.csv', index=False)


             0         1         2         3         4         5         6  \
0     0.243000  0.216000  1.045000  0.621000  0.963000  0.405000  0.437000   
1     0.253690  0.253690  0.253690  0.253690  0.253690  0.094000  0.044000   
2     0.102000  0.058000  0.050000  0.065000  0.063000  0.105000  0.069000   
3     0.347000  0.315000  0.268000  0.288000  0.314000  0.325000  0.274000   
4     0.320000  0.274000  0.284000  0.568000  1.312000  1.687000  1.326000   
...        ...       ...       ...       ...       ...       ...       ...   
3122  0.062465  0.062465  0.062465  0.062465  0.062465  0.062465  0.062465   
3123  0.136000  0.207000  0.127000  0.167000  0.148000  0.063000  0.137000   
3124  0.180000  0.125000  0.049000  0.049000  0.048000  0.049000  0.046000   
3125  0.117000  0.101000  0.168000  0.102000  0.103000  0.168000  0.105000   
3126  0.192000  0.158000  0.136000  0.038000  0.088000  0.075000  0.163000   

             7         8      9  ...     12854     12855     12

In [ ]:
idx_with_nan = data_test.isna().values.flatten()
pred =  data_test_imputed.values.flatten()[idx_with_nan]
submission_example = pd.DataFrame(
    data={'ID': [i for i in range(len(pred))],
          'TARGET': pred
          }
    )
print(submission_example.to_csv('catboost100.csv', index=False))
print(submission_example.isnull().values.any())
pred.shape

In [23]:
pred

array([0.49914933, 0.49914933, 0.49914933, ..., 0.22681973, 0.22681973,
       0.22681973])